title: Do IT
url: https://D01T.github.io
timezone: Asia/Seoul
permalink: pretty

paginate: 5
paginate_path: "/page/:num/"

collections:
  authors:
    output: true
    permalink: /authors/:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

kramdown:
  input: GFM

sass:
  style: compressed
