title: Do IT
url: https://D01T.github.io
timezone: Asia/Seoul
permalink: pretty

paginate: 5
paginate_path: "/page/:num/"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM

sass:
  style: compressed
